# Reference: http://beta.awsdocs.com/infrastructure_as_code/cloudformation/applications/jenkins_cf_deployment/

AWSTemplateFormatVersion: "2010-09-09"

Resources:
  JenkinsServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2}}"
      Tags:
        - Key: "Name"
          Value: "Jenkins_Server"
      SecurityGroups:
        - !Ref JenkinsSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        amazon-linux-extras install -y java-openjdk11
        yum install -y jenkins
        service jenkins start
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Jenkins_Security_Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

